name: VynkChatLists Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    name: Run VynkChatLists Tests
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Trust Swift Macros
        run: |
          defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

      - name: Run VynkChatLists Tests
        run: |
          xcodebuild test \
            -project Vynk.xcodeproj \
            -scheme VynkChatLists \
            -destination "platform=iOS Simulator,name=iPhone 16 Plus" \
            -skipMacroValidation
